@WebApi_HostAddress = http://localhost:5017

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/shoppinglists
Content-Type: application/json

{
  "name": "Weekly Groceries"
}

###
